; ══════════════════════════════════════════════════════════════
;  SC-IES — Smart Campus Intelligent Environment System
;  PlatformIO Project Configuration
;  Board : Arduino Mega 2560
;  Sim   : Wokwi VS Code Extension
; ══════════════════════════════════════════════════════════════

[env:megaatmega2560]
platform  = atmelavr
board     = megaatmega2560
framework = arduino

lib_deps =
    adafruit/DHT sensor library @ ^1.4.4
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

monitor_speed = 115200
build_flags   = -DDEBUG
